import type { KnownTargetId } from "@pluginfinity/targets";
import type { EmittedFile } from "./emit.js";
import { HOOK_LIB_FILES } from "./hook-lib.generated.js";

/** Where every build that has hooks gets the hook library, relative to the build root. */
export const HOOK_LIB_DIR = "hooks/lib/pluginfinity";

const singleQuote = (value: string): string => `'${value.replaceAll("'", `'\\''`)}'`;

/** The generated `host.sh` the library sources to learn which host it runs on. */
export const renderHostFile = (host: KnownTargetId, plugin: string, version: string): string =>
	[
		`# Generated by pluginfinity for the ${host} build. Do not edit.`,
		`PLUGINFINITY_HOST=${host}`,
		`PLUGINFINITY_PLUGIN=${singleQuote(plugin)}`,
		`PLUGINFINITY_LIB_VERSION=${version}`,
		"",
	].join("\n");

/** The hook library, its `host.sh` and the `tools.sh` tool map, as one target's build writes them. */
export const hookLibFiles = (
	host: KnownTargetId,
	plugin: string,
	version: string,
	toolMap: string,
): ReadonlyArray<EmittedFile> => [
	...HOOK_LIB_FILES.map((file) => ({ path: `${HOOK_LIB_DIR}/${file.name}`, content: file.content })),
	{ path: `${HOOK_LIB_DIR}/host.sh`, content: renderHostFile(host, plugin, version) },
	{ path: `${HOOK_LIB_DIR}/tools.sh`, content: toolMap },
];
