import type { Target } from "@pluginfinity/core";

const singleQuote = (value: string): string => `'${value.replaceAll("'", `'\\''`)}'`;

/**
 * The component names a target builds, as `hook_has` answers them.
 *
 * @internal
 */
export interface ToolMapComponents {
	readonly skills: ReadonlyArray<string>;
	readonly agents: ReadonlyArray<string>;
	readonly monitors: ReadonlyArray<string>;
}

/**
 * The generated `tools.sh` the hook library sources to spell a Claude tool
 * name the way the host spells it at run time.
 *
 * @remarks
 * `plugin` is the plugin's Claude name: Claude Code namespaces a plugin's MCP
 * tools with it, so a hook sees an own tool as
 * `mcp__plugin_<plugin>_<server>__<tool>` on every host, and the run-time
 * template's `{plugin}` is filled from it. Names the target leaves unresolved
 * are omitted, which `hook_tool_name` reports as no spelling.
 *
 * @internal
 */
export const renderToolMap = (
	target: Target,
	plugin: string,
	servers: ReadonlyArray<string>,
	has: ToolMapComponents,
): string => {
	const runtime = target.tools.runtime;
	const pairs = Object.entries(runtime.names).flatMap(([name, spelled]) =>
		typeof spelled === "string" ? [`${name}=${spelled}`] : [],
	);
	return [
		"# Generated by pluginfinity. Do not edit.",
		`_PF_TOOLS=${singleQuote(pairs.join("\n"))}`,
		`_PF_TOOLS_PLUGIN=${singleQuote(plugin)}`,
		`_PF_TOOLS_MCP=${singleQuote(runtime.mcp)}`,
		`_PF_TOOLS_SERVERS=${singleQuote(servers.join(" "))}`,
		`_PF_TOOLS_UNLISTED=${runtime.unlisted}`,
		`_PF_HAS_SKILLS=${singleQuote(has.skills.join(" "))}`,
		`_PF_HAS_AGENTS=${singleQuote(has.agents.join(" "))}`,
		`_PF_HAS_MONITORS=${singleQuote(("path" in target.monitors ? has.monitors : []).join(" "))}`,
		`_PF_HAS_SERVERS=${singleQuote(servers.join(" "))}`,
		"",
	].join("\n");
};
