import { assert, describe, it } from "@effect/vitest";
import { HOOK_LIB_FILES } from "../src/hook-lib.generated.js";
import { HOOK_LIB_DIR, hookLibFiles, renderHostFile } from "../src/hook-lib.js";

describe("hookLibFiles", () => {
	it("writes every library file plus host.sh and tools.sh under hooks/lib/pluginfinity", () => {
		const files = hookLibFiles("copilot", "demo", "1.2.3", "TOOLS");
		assert.deepStrictEqual(
			files.map((file) => file.path),
			[
				...HOOK_LIB_FILES.map((file) => `${HOOK_LIB_DIR}/${file.name}`),
				`${HOOK_LIB_DIR}/host.sh`,
				`${HOOK_LIB_DIR}/tools.sh`,
			],
		);
		assert.isTrue(
			files.every((file) => file.mode === undefined),
			"generated files take the generated mode",
		);
	});

	it("host.sh names the host, plugin and library version", () => {
		assert.strictEqual(
			renderHostFile("claude", "demo", "1.2.3"),
			"# Generated by pluginfinity for the claude build. Do not edit.\nPLUGINFINITY_HOST=claude\nPLUGINFINITY_PLUGIN='demo'\nPLUGINFINITY_LIB_VERSION=1.2.3\n",
		);
	});

	it("host.sh quotes the plugin name", () => {
		assert.include(renderHostFile("claude", "it's a plugin", "1"), `PLUGINFINITY_PLUGIN='it'\\''s a plugin'`);
	});
});
