// Embed hook-lib/*.sh into src/hook-lib.generated.ts so the engine can write
// the hook library into builds with no asset on disk at run time. Run with
// `pnpm --filter @pluginfinity/engine hook-lib:embed`; a test fails when the
// two disagree.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));
const files = readdirSync(`${root}hook-lib`)
	.filter((name) => name.endsWith(".sh"))
	.sort()
	.map((name) => ({ name, content: readFileSync(`${root}hook-lib/${name}`, "utf8") }));

writeFileSync(
	`${root}src/hook-lib.generated.ts`,
	`// Generated by scripts/embed-hook-lib.ts from hook-lib/*.sh. Do not edit.

/** The hook library's files, embedded so a build needs no asset on disk. */
export const HOOK_LIB_FILES: ReadonlyArray<{ readonly name: string; readonly content: string }> = ${JSON.stringify(files, null, "\t")};
`,
);
