// Embed hook-lib/*.sh, server-lib/*.sh, log-lib/*.sh, monitor-lib/*.sh and env-lib/*.sh into
// src/{hook,server,log,monitor,env}-lib.generated.ts so the engine can write the libraries into builds
// with no asset on disk at run time. Run with
// `pnpm --filter @pluginfinity/engine hook-lib:embed`; a test fails when the
// sources and the generated files disagree.
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("../", import.meta.url));

const embed = (dir: string, out: string, constName: string, doc: string): void => {
	const files = readdirSync(`${root}${dir}`)
		.filter((name) => name.endsWith(".sh"))
		.sort()
		.map((name) => ({ name, content: readFileSync(`${root}${dir}/${name}`, "utf8") }));
	writeFileSync(
		`${root}src/${out}`,
		`// Generated by scripts/embed-hook-lib.ts from ${dir}/*.sh. Do not edit.

/** ${doc} */
export const ${constName}: ReadonlyArray<{ readonly name: string; readonly content: string }> = ${JSON.stringify(files, null, "\t")};
`,
	);
};

embed(
	"hook-lib",
	"hook-lib.generated.ts",
	"HOOK_LIB_FILES",
	"The hook library's files, embedded so a build needs no asset on disk.",
);
embed(
	"server-lib",
	"server-lib.generated.ts",
	"SERVER_LIB_FILES",
	"The server library's files, embedded so a build needs no asset on disk.",
);
embed(
	"log-lib",
	"log-lib.generated.ts",
	"LOG_LIB_FILES",
	"The logging library's files, embedded so a build needs no asset on disk.",
);
embed(
	"monitor-lib",
	"monitor-lib.generated.ts",
	"MONITOR_LIB_FILES",
	"The monitor library's files, embedded so a build needs no asset on disk.",
);
embed(
	"env-lib",
	"env-lib.generated.ts",
	"ENV_LIB_FILES",
	"The session env library's files, embedded so a build needs no asset on disk.",
);
