# Generated by pluginfinity. Do not edit.
_PF_TOOLS='Read=view
Bash=bash
Edit=edit
MultiEdit=edit
Write=create
Agent=task
Task=task
Grep=grep
Glob=glob
WebFetch=web_fetch
WebSearch=web_search
Skill=skill'
_PF_TOOLS_PLUGIN='pluginfinity-dogfood'
_PF_TOOLS_MCP='{server}-{tool}'
_PF_TOOLS_SERVERS='dogfood'
_PF_TOOLS_UNLISTED=unresolved
_PF_HAS_SKILLS='env-probe hook-eval'
_PF_HAS_AGENTS='eval-subagent'
_PF_HAS_MONITORS=''
_PF_HAS_SERVERS='dogfood'
